webserver:
  hostname: nginx
  domainname: quotas
  env_file:
    - .env
  build: ./docker/web
  container_name: "quotas_web"
  ports:
    - "8081:81"
  volumes:
    - ./:/quotas
    - ./docker/web/api.conf:/etc/nginx/conf.d/api.conf
    - ./docker/log/nginx:/var/log/nginx
  restart: always
  links:
    - application
    - database
application:
  env_file:
    - .env
  build: ./docker/app
  container_name: "quotas_application"
  environment:
    PHP_IDE_CONFIG: "serverName=API Server"
  volumes:
    - ./:/quotas
  ports:
    - "1338:1338"
  restart: always
composer:
  build: ./docker/composer
  container_name: "quotas_composer"
  volumes_from:
  - application
database:
  env_file:
    - .env
  image: mysql:latest
  container_name: "quotas_mysql"
  command: "--innodb_use_native_aio=0 --wait_timeout=28800"
  environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  volumes:
    - ./docker/data:/var/lib/mysql
    - ./:/code
  restart: always
  ports:
    - "3306:3306"
