<?php

namespace App\Enum\Property;

Enum OtherDisclosuresEnum: int
{
    case AGENT_HAS_FINANCIAL_INTEREST = 1;
    case AGENT_HAS_NOT_INSPECTION_PROPERTY = 2;
    case AGENT_RELATED_TO_SELLER = 3;
    case AGRICULTURAL_ZONE = 4;
    case BUILDING_PERMIT = 5;
    case CERTAIN_FIXED_REAL_PROPERTY_EXCLUDED = 6;
    case COASTAL_JURISDICTION = 7;
    case CORPORATE_OWNERSHIP = 8;
    case ESTOPPEL_CERTIFICATE = 9;
    case FIRST_RIGHT_OF_REFUSAL = 10;
    case FIXER_HANDYMAN_SPECIAL = 11;
    case FORECLOSURE_OR_SHORT_SALE = 12;
    case HISTORICAL_PRESERVATION_DISTRICT = 13;
    case HOME_WARRANTY_SPLIT_50_TO50 = 14;
    case HOME_WARRANTY = 15;
    case LEASED_LAND = 16;
    case MELLO_ROSS = 17;
    case PENDING_LITIGATION = 18;
    case POOL_OR_SPA_INSPECTION = 19;
    case PROPERTY_INSPECTION = 20;
    case RENT_CONTROL = 21;
    case RENTAL_RESTRICTIONS = 22;
    case ROAD_MAINTENANCE_AGREEMENT = 23;
    case SCHOOL_DISTRICT_UNDER_COURT_RULING = 24;
    case SELLER_IS_LICENSED_REAL_ESTATE_AGENT = 25;
    case SEWER_LATERAL_INSPECTION = 26;
    case SUBJECT_TO_1031_TAX_EXCHANGE = 27;
    case TERMITE_REPORT = 28;
    case TIMBER_PRODUCTION_ZONE = 29;
    case TREE_ORDINANCE = 30;
    case UNDERGROUND_STORAGE_TANK = 31;
    case WATER_TEST_LOGS = 32;
    case WELL_PRODUCTION_LOG = 33;
    case NONE = 34;
}
